# Generated by Django 4.0.1 on 2022-01-18 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time_mon', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('closing_time_mon', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('opening_time_tue', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('closing_time_tue', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('opening_time_wed', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('closing_time_wed', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('opening_time_thu', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('closing_time_thu', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('opening_time_fri', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('closing_time_fri', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('opening_time_sat', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('closing_time_sat', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('opening_time_sun', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
                ('closing_time_sun', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('timings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timings')),
            ],
        ),
    ]
